# Generated by Django 2.2.5 on 2019-09-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth', models.DateTimeField()),
                ('collection', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.DateTimeField()),
                ('doctor', models.CharField(max_length=255)),
                ('formId', models.CharField(max_length=255)),
            ],
        ),
    ]
